application: mashup321com
version: 1
runtime: python27
api_version: 1
threadsafe: yes


libraries:
- name: webapp2
  version: latest
- name: jinja2                                                                  
  version: latest                                                               
- name: markupsafe                                                              
  version: latest 
  
handlers:
- url: /css
  static_dir: css
  
- url: /js
  static_dir: js

- url: /imgs
  static_dir: imgs

- url: /.*
  script: main.app

  